services:
  vue-production:
    build:
      context: .
      target: production
      args:
        VITE_API_URL: https://starlink98.cloud/api
    image: my-front-production:latest
    container_name: my-front-production-container
    ports:
      - 3000:80